### ISSUE TITLE
Implement documentation in Markdown

### ISSUE THREAD

**Issue by shalvah** [isocroft/Jollof#10]
Okay, not really a bug or something, but I feel it would make it easier to read and understand, without having to clone the repo, and on mobile too.

**Comment by isocroft** [comment]
You are very right. Working on this at the moment.

Thanks for the idea.

**Comment by shalvah** [comment]
I can take up the issue if you'd like.

**Comment by isocroft** [comment]
@shalvah I'll be glad. Please, go ahead. I have just pushed an **EASYDOCS.md** file which contains a few things. Feel free to update it as necessary.

Thank you so very much for opting to take on this. I appreciate. The load on me concerning this repo is quite enormous.

**Comment by shalvah** [comment]
I noticed this in the easydocs file...

> This command will add an entry into the _setup.php_ file inside the __routes__ folder.

 ```bash
                   
    $ php jollof make:route /home GET

```

> Let's now create a simple controller file by running the command below.
> This command will drop a _Home.php_ file inside the __routes__ folder.

>> NOTE: the name of the controller file <strong>MUST</strong> be the same as the first part of the route url.
             
 ```bash

    $ php jollof make:controller home

```
(Forgive any formatting; I'm on mobile.)

So, I'm thinking... Since the controller must be named same as route, why not have a command (or a flag to the route-generating command) that creates the controller file too? I believe he idea behind using commands like these is to simplify things by generating oft-used templates, not just to avoid clicking "New File".

**Comment by isocroft** [comment]
Oh! my bad. I'll correct that error in the *EASYDOCS.md* file. 

>Adding a flag to the route-generating command that creates the controller file

I think this's wouldn't be a bad idea. Using one stone to kill two birds. I'll look into this. Infact i'll implement it.

**Comment by isocroft** [comment]
So, now we have the following already implemented - **set-controller** serves as the flag to create the controller.

```bash

    $ php jollof make:route /api/contents/@id POST set-controller

```
@shalvah what do you think ?

**Comment by shalvah** [comment]
Not bad, but I think we could provide a single-letter flag too (my hand
would be paining me with all that typing). Maybe `-c`? Also, don't forget
the dashes normally used for flags.

**Comment by isocroft** [comment]
@shalvah,  a single letter it is "-c". Will have it done soon

**Comment by isocroft** [comment]
@shalvah , I have already providered 2 alternatives '--controller', '-c'. One is a single-letter flag and the other is a full-option flag (long-option). Pushing v0.0.4 updates in an hours time from now.

**Comment by isocroft** [comment]
on the advice of a developer, who introduced me to https://semver.org, i actually re-versioned **Jollof** to begin from v0.0.2 (start) -> v0.0.4 (current)
