### ISSUE TITLE
Issue with README.md statement

### ISSUE THREAD

**Issue by mykeels** [isocroft/Jollof#9]
Awesome repo!

However, this statement about the close-knit-nature of Routes to Controllers appears to be false: *"It's a new way of thinking about the way applications should be crafted!"* 

I suggest it's looked into.

**Comment by isocroft** [comment]
Good observation @mykeels 

How do you mean ? Can you elucidate further ?

**Comment by shalvah** [comment]
I think he means that the statement isn't correct, because traditionally MVC routes made use of the `controller/action` paradigm, so saying this is new is misleading. See also https://www.codeproject.com/tips/573454/routing-in-mvc

**Comment by mykeels** [comment]
Yea @shalvah. I'm sorry, @isocroft ... I couldn't reply earlier. 

I know for a fact that ASP.NET MVC makes use of the `~/controller/action/{id}` route by default, which makes that assertion wrong.

I think it should be modified ...

**Comment by isocroft** [comment]
i read this: https://www.codeproject.com/tips/573454/routing-in-mvc

I will effect the change in the **README.md** file soonest. Funny, I'm not an ASP.NET Dev. So i didn't think it had it already.

Thank a lot @mykeels and @shalvah for bringing this to my attention to this.

**Comment by isocroft** [comment]
@mykeels and @shalvah check out the changes to the README.md file. Just to make sure everything is alright.

**Comment by isocroft** [comment]
Okay, i think it's safe to say i have dealt well enough with this one. :100:
